---
applications:
- name: task-engine
  memory: 512M
  disk_quota: 512M
  instances: 1
  timeout: 180
  no-route: true
  buildpack: dicf_python_buildpack_1629_cflinuxfs3
  stack: cflinuxfs3
  health-check-type: process
  env:
    BROKER_NAME: BROKER
    BACKEND_NAME: REDIS_INSTANCE
    POSTGRES_CREDS_NAME: POSTGRES
    PYTHONPATH: app
    ENVIRONMENT: prod
  services:
  - BROKER
  - REDIS_INSTANCE
  - POSTGRES